### PR TITLE
Add feature to enable the bg thread (enabled by default)

### PR DESCRIPTION
**Pull request by gnzlbg**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Certainly! I've invited you as an owner to those two crate so you should be able to publish

**Comment by gnzlbg** [comment]
So I am a maintainer on github but not on crates.io :/

**Comment by alexcrichton** [comment]
I think you should have invites?

**Comment by gnzlbg** [comment]
Ah, yes! accepted!

**Pull request merged**
