### PR TITLE
Add description for MALLOC_CONF environment variable

### PR DESCRIPTION
**Pull request by shinnya**
Hi, all. 

This PR adds description about configuring `MALLOC_CONF` . Could you please review this change? 

 I hope this description saves someone's time.

### CODE REVIEW

**Comment by gnzlbg** [comment]
See https://github.com/gnzlbg/jemallocator/blob/master/jemalloc-sys/readme.md#environment-variables

**Comment by shinnya** [comment]
Thank you for your quick reply. 

Let me confirm what you're saying. Could you mean there is already enough documentation for configuring `MALLOC_CONF` environment variable. For me, the description you mentioned looks compile time options, but the description I've added is about runtime configuration.

**Comment by gnzlbg** [comment]
> Could you mean there is already enough documentation for configuring `MALLOC_CONF` environment variable?

No, definitely not! What I'm saying is that this is something that probably belongs as documentation for the `jemalloc-sys` crate. Looking at it I understand that this documentation can be hard to find. 

For example, the `jemalloc-sys` docs already point to the jemalloc documentation upstream here under API documentaiton (https://github.com/gnzlbg/jemallocator/blob/master/jemalloc-sys/README.md#documentation) which is the definitive reference about all jemalloc options. 

While the README covers the compile-time options, the API docs of jemalloc-sys: https://github.com/gnzlbg/jemallocator/blob/master/jemalloc-sys/src/lib.rs#L582 expand quite a bit on how to use `malloc_conf`.

I'm not sure if that's enough for you, but I could understand why not. `malloc_conf` is tricky to use correctly. 

So I think the fix here would be to improve the docs of `malloc_conf`, but probably we also need to improve the discoverability of these docs.

**Comment by shinnya** [comment]
I appreciate your detailed description. 

> So I think the fix here would be to improve the docs of `malloc_conf`, but probably we also need to improve the discoverability of these docs.

I absolutely agree with you. For me, I was in trouble with setting `MALLOC_CONF` environment variable via `jemallocator`(`jemalloc-sys`) due to its implicit behavior. The behavior I mention is that `jemalloc-sys` compiles `jemalloc` with `--with-jemalloc-prefix=_rjem_` configure option by default. Yes, Of course, someone who is very careful could find the following document from `jemalloc-sys`:

> unprefixed_malloc_on_supported_platforms: when disabled, configure jemalloc with --with-jemalloc-prefix=_rjem_.

**Comment by gnzlbg** [comment]
> The behavior I mention is that `jemalloc-sys` compiles `jemalloc` with `--with-jemalloc-prefix=_rjem_` configure option by default.

Yeah, this is confusing. The problem here is that turning that option on by default still uses the `_rjem_` prefix for some targets because compiling without the prefix is not supported. So it is less surprising to use `_rjem_` everywhere, than to use `_rjem_` in some targets but not others, unless you opt into it.

**Comment by shinnya** [comment]
I checked 01b2dc89238a35b38f8d7b62c2ef876ed7641b2f out. Thank you for considering my request.

**Pull request closed without merging**
